# Generated by Django 3.1.4 on 2020-12-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservote',
            name='question',
        ),
    ]
