# Generated by Django 3.1.4 on 2020-12-14 12:51

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_uservote_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='uservote',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('user_id', 'vote', 'question'), name='one_vote_perQuestion'),
        ),
    ]
