# Generated by Django 3.1.4 on 2020-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201214_1252'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uservote',
            name='one_vote_perQuestion',
        ),
        migrations.AddConstraint(
            model_name='uservote',
            constraint=models.UniqueConstraint(fields=('user_id', 'vote', 'question'), name='one_vote_Question'),
        ),
        migrations.AddConstraint(
            model_name='uservote',
            constraint=models.UniqueConstraint(fields=('user_id', 'vote'), name='one_vote_perQuestion'),
        ),
    ]
