# Generated by Django 3.1.4 on 2020-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20201214_1317'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uservote',
            name='one_vote_Question',
        ),
        migrations.AddConstraint(
            model_name='uservote',
            constraint=models.UniqueConstraint(fields=('vote', 'user_id'), name='one_vote_Question'),
        ),
    ]
