# Generated by Django 3.1.4 on 2020-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20201214_1642'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('c_name', 'question'), name='vote_question'),
        ),
    ]
